apiVersion: v1
kind: Secret
metadata:
  name: <MY ORG NAME>-secret # NOME DA SECRET
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repo-creds # TIPO PARA SER USADO EM MAIS DE UM REPOSITORIO
stringData:
  type: git
  url: https://github.com/<ORG_NAME>
  # Exemplo com Github App
  githubAppID: ""
  githubAppInstallationID: ""
  githubAppPrivateKey: |
    -----BEGIN RSA PRIVATE KEY-----
    -----END RSA PRIVATE KEY-----
---
apiVersion: v1
kind: Secret
metadata:
  name: <MY-REPO-1>-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/<ORG_NAME>/<REPO_NAME_1>.git
---
apiVersion: v1
kind: Secret
metadata:
  name: <MY-REPO-2>-secret
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: https://github.com/<ORG_NAME>/<REPO_NAME_2>.git

  